apiVersion: v1
kind: Service
metadata:
  name: "keptn-gitea-provisioner"
  labels:
    app.kubernetes.io/name: keptn-gitea-provisioner
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: keptn-gitea-provisioner
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
